name: ci

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # presecurity: ignore
      - uses: actions/setup-python@v5 # presecurity: ignore
        with:
          python-version: "3.12"
      - run: python -m pip install -e .
      - run: python -m pip install pytest
      - run: pytest
